"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 13:53:24.983270

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_events'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('avatar_data_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('uq_users_stripe_customer_id'))
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('auth_method', sa.Enum('local', 'google', 'magic_link', name='auth_method_enum'), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_sessions_expires_at_gt_created_at')),
    sa.ForeignKeyConstraint(['replaced_by'], ['auth_sessions.id'], name=op.f('fk_auth_sessions_replaced_by_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_auth_sessions_auth_method'), ['auth_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_auth_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_auth_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_auth_sessions_user_id_is_revoked', ['user_id', 'is_revoked'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email_to_verify', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > sent_at', name=op.f('ck_email_verifications_expires_at_gt_sent_at')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verifications')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verifications_token_hash'))
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('first_party_auth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_first_party_auth_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_first_party_auth')),
    sa.UniqueConstraint('user_id', name=op.f('uq_first_party_auth_user_id'))
    )
    op.create_table('magic_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_ip', sa.String(), nullable=True),
    sa.Column('requester_user_agent', sa.String(), nullable=True),
    sa.CheckConstraint('expires_at > sent_at', name=op.f('ck_magic_links_expires_at_gt_sent_at')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_magic_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_magic_links_token_hash'))
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_magic_links_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_magic_links_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > sent_at', name=op.f('ck_password_resets_expires_at_gt_sent_at')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_resets_token_hash'))
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'refunded', 'partially_refunded', 'disputed', 'failed', name='purchase_status_enum'), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('stripe_charge_id', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount_subtotal_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_tax_cents', sa.BigInteger(), nullable=True),
    sa.Column('amount_total_cents', sa.BigInteger(), nullable=True),
    sa.Column('refunded_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    sa.UniqueConstraint('stripe_checkout_session_id', name=op.f('uq_purchases_stripe_checkout_session_id'))
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_purchases_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchases_stripe_charge_id'), ['stripe_charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchases_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchases_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_purchases_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('trialing', 'active', 'incomplete', 'incomplete_expired', 'past_due', 'canceled', 'unpaid', 'paused', name='subscription_status_enum'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('uq_subscriptions_stripe_subscription_id'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriptions_stripe_price_id'), ['stripe_price_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('third_party_auth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('google', name='third_party_auth_provider_enum'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('id_token_encrypted', sa.Text(), nullable=True),
    sa.Column('profile_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_third_party_auth_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_third_party_auth')),
    sa.UniqueConstraint('user_id', 'provider', 'subject', name='uq_third_party_auth_user_id_provider_subject')
    )
    with op.batch_alter_table('third_party_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_third_party_auth_third_party_auth_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_third_party_auth_third_party_auth_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_third_party_auth_third_party_auth_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('third_party_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_third_party_auth_third_party_auth_user_id'))
        batch_op.drop_index(batch_op.f('ix_third_party_auth_third_party_auth_subject'))
        batch_op.drop_index(batch_op.f('ix_third_party_auth_third_party_auth_provider'))

    op.drop_table('third_party_auth')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriptions_stripe_price_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriptions_status'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index('ix_purchases_user_id_created_at')
        batch_op.drop_index(batch_op.f('ix_purchases_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchases_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchases_stripe_charge_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchases_status'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchases_product_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_password_resets_user_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_magic_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_magic_links_magic_links_email'))

    op.drop_table('magic_links')
    op.drop_table('first_party_auth')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_email_verifications_user_id'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user_id_is_revoked')
        batch_op.drop_index(batch_op.f('ix_auth_sessions_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_auth_sessions_family_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_auth_sessions_auth_method'))

    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for enum_name in (
        'third_party_auth_provider_enum',
        'subscription_status_enum',
        'purchase_status_enum',
        'auth_method_enum',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
